version: '3'

services:
  api-db:
      image: postgres:11-alpine
      environment:
            POSTGRES_USER : test
            POSTGRES_PASSWORD: test
            POSTGRES_DB : api
      ports:
       - 5432:5432

  api-service:
    build: ./api
    environment:
        DATABASE_URL: postgresql://test:test@api-db/api
    volumes:
     - ./api/src:/home/docker/code
     - ./test-results/api-service:/home/docker/code/tests/report
    ports:
      - 5000:5000
    depends_on:
      - api-db

  api-tests:
      build: ./api-acceptance-tests
      volumes:
       - ./test-results/api-tests:/home/docker/code/newman
      depends_on:
      - api-service


  web-service:
    build: ./web
    volumes:
     - ./web/src:/home/docker/code
     - ./test-results/web-service:/home/docker/code/tests/report
    ports:
      - 5005:80

  web-tests:
      build: ./web-acceptance-tests
      volumes:
       - ./test-results/web-tests:/home/docker/code/tests/report
      depends_on:
      - web-service