version: '3'

services:
#  api-db:
#      image: postgres:11-alpine
#      environment:
#            POSTGRES_USER : test
#            POSTGRES_PASSWORD: test
#            POSTGRES_DB : api
#      ports:
#       - 5432:5432
#
#  api-service:
#    build: ./api
#    environment:
#        DATABASE_URL: postgresql://test:test@api-db/api
#    volumes:
#     - ./api/src:/home/docker/code
#     - ./test-results/api-unit:/tmp/test_report/
#    ports:
#      - 5000:5000
#    depends_on:
#      - api-db
#
#  api-tests:
#      build: ./api-acceptance-tests
#      volumes:
#       - ./test-results/api-e2e:/home/docker/code/newman
#      depends_on:
#      - api-service




  web-db:
      image: postgres:11-alpine
      environment:
            POSTGRES_USER : test
            POSTGRES_PASSWORD: test
            POSTGRES_DB : api
      ports:
       - 5432:5432

  web-service:
    build: ./web
    environment:
        DATABASE_URL: postgresql://test:test@web-db/api

    volumes:
     - ./web/src:/home/docker/code
    ports:
      - 5005:80
    depends_on:
     - web-db

  web-tests:
      build: ./web-acceptance-tests
      volumes:
       - ./test-results/web-e2e:/tmp/test_report/
      depends_on:
      - web-service